BACKUP LOG DGS_DOC TO  DISK = N'\\192.168.13.1\H\Backups Internos\Pablo\GMTAdvogados.trn' WITH NOFORMAT, NOINIT,  NAME = N'Arlanxeo-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
GO
